theme: jekyll-theme-cayman
title: Unnas
description: >
  a card game
  brought to discord by CatEyedLin
show_downloads: true
github:
  zip_url: https://github.com/CatEyedLin/Unnas/releases/download/Alpha/alpha.1.0.4.zip
  relpage_url: https://github.com/CatEyedLin/Unnas/releases
